// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lanhxxpmiqqnigrnuvyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhbmh4eHBtaXFxbmlncm51dnlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwNTgwNjIsImV4cCI6MjA4NjYzNDA2Mn0.KwwjuXF3PmiLPGsDvx-fOTUQuncB59vL0hi-ZvPeT9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});